version: 2
jobs:
  build-python36:
    docker:
      - image: python:3.6
    working_directory: ~/numerai-cli
    steps:
      - checkout
      - run: pip install .
      # TODO: add better tests
      - run: numerai docker copy-example
      - run: test -e predict.py

  build-python37:
    docker:
      - image: python:3.7
    working_directory: ~/numerai-cli
    steps:
      - checkout
      - run: pip install .
      # TODO: add better tests
      - run: numerai docker copy-example
      - run: test -e predict.py

  docker-build:
    machine: true # this allows us to use `docker` commands directly
    working_directory: ~/numerai-cli
    steps:
      - checkout
      - run: cd numerai_compute/examples/python3 && docker build -t example-python --build-arg NUMERAI_PUBLIC_ID=test --build-arg NUMERAI_SECRET_KEY=test .

  pypi-release:
    docker:
      - image: pyhton3.7
    steps:
      - checkout
      - run: pip install twine
      - run: python setup.py sdist bdist_wheel
      - run: twine upload --skip-existing --repository numerai-cli dist/* --usernam @token --passsword $PYPI_API_KEY

workflows:
  version: 2
  build:
    jobs:
      - build-python36
      - build-python37
      - docker-build
      - pypi-release:
          requires:
            - build-python36
            - build-python37
            - docker-build
          filters:
            branches:
              only: master
